INSERT INTO `bank_information`(`name`,`enabled`)values("ABHYUDAYA COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ABU DHABI COMMERCIAL BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("AHMEDABAD MERCANTILE COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("AIRTEL PAYMENTS BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("AKOLA JANATA COMMERCIAL COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ALLAHABAD BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ALMORA URBAN COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ANDHRA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ANDHRA PRAGATHI GRAMEENA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("APNA SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("AU SMALL FINANCE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("AXIS BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("B N P PARIBAS",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANDHAN BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANK OF AMERICA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANK OF BAHARAIN AND KUWAIT BSC",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANK OF BARODA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANK OF CEYLON",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANK OF INDIA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANK OF MAHARASHTRA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BANK OF TOKYO MITSUBISHI LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BARCLAYS BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BASSEIN CATHOLIC COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("BHARAT COOPERATIVE BANK MUMBAI LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CANARA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CAPITAL SMALL FINANCE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CATHOLIC SYRIAN BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CENTRAL BANK OF INDIA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CHINATRUST COMMERCIAL BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CITI BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CITIZEN CREDIT COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CITY UNION BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CORPORATION BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALYON BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("CREDIT SUISEE AG",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DCB BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DENA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DEOGIRI NAGARI SAHAKARI BANK LTD. AURANGABAD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DEUSTCHE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DEVELOPMENT BANK OF SINGAPORE",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DHANALAKSHMI BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DOHA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DOHA BANK QSC",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("DOMBIVLI NAGARI SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("EQUITAS SMALL FINANCE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ESAF SMALL FINANCE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("EXPORT IMPORT BANK OF INDIA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("FEDERAL BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("FINCARE SMALL FINANCE BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("FINO PAYMENTS BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("FIRSTRAND BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("G P PARSIK BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("HARYANA STATE COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("HDFC BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("HIMACHAL PRADESH STATE COOPERATIVE BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("HSBC BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ICICI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("IDBI BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("IDFC BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("IDUKKI DISTRICT CO OPERATIVE BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("INDIAN BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("INDIAN OVERSEAS BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("INDUSIND BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("INDUSTRIAL BANK OF KOREA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("JALGAON JANATA SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("JAMMU AND KASHMIR BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("JANAKALYAN SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("JANASEVA SAHAKARI BANK BORIVLI LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("JANASEVA SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("JANATA SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("JP MORGAN BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KALUPUR COMMERCIAL COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KALYAN JANATA SAHAKARI BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KARNATAKA BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KARNATAKA VIKAS GRAMEENA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KARUR VYSYA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KEB Hana Bank",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KERALA GRAMIN BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KOTAK MAHINDRA BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("KOZHIKODE DISTRICT COOPERATIAVE BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("LAXMI VILAS BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("MAHANAGAR COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("Maharashtra Gramin Bank",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("MAHARASHTRA STATE COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("MASHREQBANK PSC",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("MIZUHO BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("NAGAR URBAN CO OPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("NAGPUR NAGARIK SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("NATIONAL AUSTRALIA BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("NATIONAL BANK OF ABU DHABI PJSC",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("NEW INDIA COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("NKGSB COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("NUTAN NAGARIK SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ORIENTAL BANK OF COMMERCE",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PAYTM PAYMENTS BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PRAGATHI KRISHNA GRAMIN BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PRATHAMA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PRIME COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PT BANK MAYBANK INDONESIA TBK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PUNJAB AND MAHARSHTRA COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PUNJAB AND SIND BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("PUNJAB NATIONAL BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("RABOBANK INTERNATIONAL",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("RAJGURUNAGAR SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("RAJKOT NAGRIK SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("RBL Bank Limited",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("RESERVE BANK OF INDIA , PAD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("RESERVE BANK OF INDIA, PAD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SAMARTH SAHAKARI BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SARASWAT COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SBER BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SBM BANK MAURITIUS LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SHIKSHAK SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SHINHAN BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SHIVALIK MERCANTILE CO OPERATIVE BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SOCIETE GENERALE",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SOLAPUR JANATA SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SOUTH INDIAN BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("STANDARD CHARTERED BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("STATE BANK OF INDIA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SUMITOMO MITSUI BANKING CORPORATION",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SURAT NATIONAL COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SURYODAY SMALL FINANCE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SUTEX COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("SYNDICATE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("TAMILNAD MERCANTILE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("TELANGANA STATE COOP APEX BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("TEXTILE TRADERS CO OPERATIVE BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("TEXTILE TRADERS CO-OPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE BANK OF NOVA SCOTIA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE BARAMATI SAHAKARI BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE COSMOS CO OPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE DELHI STATE COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE GREATER BOMBAY COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE GUJARAT STATE COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE HASTI COOP BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE JALGAON PEOPELS COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE KANGRA CENTRAL COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE KANGRA COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE KARAD URBAN COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE MEHSANA URBAN COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE MUNICIPAL COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE NAINITAL BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE NASIK MERCHANTS COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE NAVNIRMAN CO-OPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE PANDHARPUR URBAN CO OP. BANK LTD. PANDHARPUR",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE RAJASTHAN STATE COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE ROYAL BANK OF SCOTLAND N V",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE SEVA VIKAS COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE SHAMRAO VITHAL COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE SINDHUDURG DISTRICT CENTRAL COOP BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE SURAT DISTRICT COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE SURATH PEOPLES COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE TAMIL NADU STATE APEX COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE THANE BHARAT SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE VARACHHA COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE VISHWESHWAR SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE WEST BENGAL STATE COOPERATIVE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("THE ZOROASTRIAN COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("TJSB SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("TJSB SAHAKARI BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("UCO BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("Ujjivan Small Finance Bank Limited",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("UNION BANK OF INDIA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("UNITED BANK OF INDIA",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("UNITED OVERSEAS BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("UTKARSH SMALL FINANCE BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("VASAI VIKAS SAHAKARI BANK LIMITED",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("VASAI VIKAS SAHAKARI BANK LTD",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("VIJAYA BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("WESTPAC BANKING CORPORATION",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("WOORI BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("YES BANK",1);
INSERT INTO `bank_information`(`name`,`enabled`)values("ZILA SAHAKRI BANK LIMITED GHAZIABAD",1);
