INSERT INTO `state`(`name`,`enabled`)values("ANDAMAN AND NICOBAR ISLAND",1);
INSERT INTO `state`(`name`,`enabled`)values("ANDHRA PRADESH",1);
INSERT INTO `state`(`name`,`enabled`)values("ARUNACHAL PRADESH",1);
INSERT INTO `state`(`name`,`enabled`)values("ASSAM",1);
INSERT INTO `state`(`name`,`enabled`)values("BIHAR",1);
INSERT INTO `state`(`name`,`enabled`)values("CHANDIGARH",1);
INSERT INTO `state`(`name`,`enabled`)values("CHHATTISGARH",1);
INSERT INTO `state`(`name`,`enabled`)values("DADRA AND NAGAR HAVELI",1);
INSERT INTO `state`(`name`,`enabled`)values("DAMAN AND DIU",1);
INSERT INTO `state`(`name`,`enabled`)values("DELHI",1);
INSERT INTO `state`(`name`,`enabled`)values("GOA",1);
INSERT INTO `state`(`name`,`enabled`)values("GUJARAT",1);
INSERT INTO `state`(`name`,`enabled`)values("HARYANA",1);
INSERT INTO `state`(`name`,`enabled`)values("HIMACHAL PRADESH",1);
INSERT INTO `state`(`name`,`enabled`)values("JAMMU AND KASHMIR",1);
INSERT INTO `state`(`name`,`enabled`)values("JHARKHAND",1);
INSERT INTO `state`(`name`,`enabled`)values("KARNATAKA",1);
INSERT INTO `state`(`name`,`enabled`)values("KERALA",1);
INSERT INTO `state`(`name`,`enabled`)values("LAKSHADWEEP",1);
INSERT INTO `state`(`name`,`enabled`)values("MADHYA PRADESH",1);
INSERT INTO `state`(`name`,`enabled`)values("MAHARASHTRA",1);
INSERT INTO `state`(`name`,`enabled`)values("MANIPUR",1);
INSERT INTO `state`(`name`,`enabled`)values("MEGHALAYA",1);
INSERT INTO `state`(`name`,`enabled`)values("MIZORAM",1);
INSERT INTO `state`(`name`,`enabled`)values("NAGALAND",1);
INSERT INTO `state`(`name`,`enabled`)values("NEW DELHI",1);
INSERT INTO `state`(`name`,`enabled`)values("ODISHA",1);
INSERT INTO `state`(`name`,`enabled`)values("PUDUCHERRY",1);
INSERT INTO `state`(`name`,`enabled`)values("PUNJAB",1);
INSERT INTO `state`(`name`,`enabled`)values("RAJASTHAN",1);
INSERT INTO `state`(`name`,`enabled`)values("SIKKIM",1);
INSERT INTO `state`(`name`,`enabled`)values("TAMIL NADU",1);
INSERT INTO `state`(`name`,`enabled`)values("TELANGANA",1);
INSERT INTO `state`(`name`,`enabled`)values("TRIPURA",1);
INSERT INTO `state`(`name`,`enabled`)values("UTTAR PRADESH",1);
INSERT INTO `state`(`name`,`enabled`)values("UTTARAKHAND",1);
INSERT INTO `state`(`name`,`enabled`)values("WEST BENGAL",1);
